### PR TITLE
draft-ietf-ippm-ioam-data-integrity: Major review

### PR DESCRIPTION
**Pull request by IurmanJ**
Major revision of draft-ietf-ippm-ioam-data-integrity. Here is a summary
of changes:
 - integrity protection of **data fields** *only*.
 - section defining Integrity Protected Option-Types (+ integrity
protection subheader) was restructured.
 - following point 1, section defining methods was restructured and the
procedure (as generic as possible) was  updated accordingly.
 - removed DEX citation/reference (out of scope, see procedure in 3).
 - replay protection not totally in scope: moved to security section.
 - some edits here and there

Example for each Option-Type, following the new procedure defined in the
draft:
 [Trace Option-Types]
  - encap:   sign(Nonce || hash(data fields))
  - transit: sign(Signature || hash(data fields))
  - decap:   same as transit (or validator)

  -> the validator uses recorded node-ids to map ids with keys and
recreates the signature iteratively, following the same procedure in the
same order.

 [POT (Type 0) Option-Type]
  - encap:   sign(Nonce || hash(data fields minus Cumulative field))
  - transit: all data fields involved are modified in-place (Cumulative
field) -> do not sign
  - decap:   same as transit (or validator)

  -> only the encapsulating node has signed the data fields, so the
validator easily recreates the signature.

 [E2E Option-Type]
  - encap:   sign(Nonce || hash(data fields))
  - transit: none
  - decap:   no data field involved -> do not sign (or validator)

  -> only the encapsulating node has signed the data fields, so the
validator easily recreates the signature.

 [DEX Option-Type]
  - encap: does not contain any data fields -> do not use Integrity
Protected Option-Type.

Notes:
 - should we use "IOAM-Data-Fields" as defined in
draft-ietf-ippm-ioam-data or keep "data fields" as currently?
 - Validator: hard to keep it generic. Also, should we mention the
special case with Trace Option-Types and Opaque State Snapshot? Not sure
it is really that useful as implementors would figure it out obviously,
and I suspect that it would overload the paragraph. Thoughts?

Resolves inband-oam/ietf#238
Resolves inband-oam/ietf#239
Resolves inband-oam/ietf#240
Resolves inband-oam/ietf#242

Signed-off-by: Justin Iurman <justin.iurman@uliege.be>

### CODE REVIEW

**Comment by brockners** [comment]
LGTM - two notes:

* On your question: "should we use "IOAM-Data-Fields" as defined in draft-ietf-ippm-ioam-data". IMHO it would be a good idea to use IOAM-Data-Fields throughout. Even draft-ietf-ippm-ioam-data-17 isn't really consistent - as there are quite a few places that use "IOAM data fields" instead. Something for clean-up by the RFC editor. 
* Section "5.2.  IOAM Integrity Protection Algorithm Suite Registry" is to list a set of suitable pairs of algorithms for signature and algorithm. Or in other terms, there could be more than a single set of algorithms being used. This contradicts with what we say in e.g., section 4.3.  "Space optimized symmetric key based signing of IOAM data" - where we have a MUST for AES-256 and  SHA-256. Would you mind cleaning this up as well by using a reference to 5.2 rather than referring to algorithm pairs directly in the spec?

Thanks!

**Comment by IurmanJ** [comment]
>     * On your question: "should we use "IOAM-Data-Fields" as defined in draft-ietf-ippm-ioam-data". IMHO it would be a good idea to use IOAM-Data-Fields throughout. Even draft-ietf-ippm-ioam-data-17 isn't really consistent - as there are quite a few places that use "IOAM data fields" instead. Something for clean-up by the RFC editor.

Just pushed another commit ([fdcfa38](https://github.com/inband-oam/ietf/pull/246/commits/fdcfa38c3a255386a14d8ae90d05d2f9fb81146d)) on top of the first (did not merge them so you can see the diff more easily).

>     * Section "5.2.  IOAM Integrity Protection Algorithm Suite Registry" is to list a set of suitable pairs of algorithms for signature and algorithm. Or in other terms, there could be more than a single set of algorithms being used. This contradicts with what we say in e.g., section 4.3.  "Space optimized symmetric key based signing of IOAM data" - where we have a MUST for AES-256 and  SHA-256. Would you mind cleaning this up as well by using a reference to 5.2 rather than referring to algorithm pairs directly in the spec?

Good catch. Indeed, following the reorganization of the (sub)sections, what you mention must be modified. However, if I just use a ref to section 5.2 instead of mentioning algorithm pairs, I think it wouldn't be enough. In fact, the table in section 5.2 contains (and will contain in the future) both symmetric and asymmetric signature algorithms. Therefore, it'd be hard to say which one(s) should be used in the methods section (it'd make little sense to use, e.g., AES for the asymmetric method). Unless, for example, if we define symmetric signature algorithms first (from 0x00 to 0x80?), and the rest for asymmetric signature algorithms. Or would it be enough to use a ref to section 5.2 and add something like "for symmetric (or asymmetric resp.) signature algorithms" (and annotate sec. 5.2 for each signature algorithm)? Thoughts? BTW, shouldn't the "unassigned range" start at 0xF0 (instead of 0xEF)?

**Comment by IurmanJ** [comment]
Commit [74d0ce7](https://github.com/inband-oam/ietf/pull/246/commits/74d0ce713c9ca4ca8f84448c400ac64bf06f049d) is a first attempt at solving the problem you mentioned previously. Maybe should we specifically annotate each algo pair to distinguish those for symmetric from those for asymmetric purpose?

**Comment by brockners** [comment]
Thanks for the updates.

> As a consequence, we could say "use algorithm pairs with a symmetric (first range) (or asymmetric (second range) resp.) in the methods section.

IMHO this would be a worthwhile approach, b/c it is generic. Per your suggestion we can add a note to each table entry hinting whether the algo pair would fit a symmetric or asymmetric approach - that would help with clarity.

> BTW, shouldn't the "unassigned range" start at 0xF0 (instead of 0xEF)? Or even start at 0x3 for now?

Agreed. Given that assignment would happen via the Standards Action process, it might indeed be consistent to flag the entire range of numbers that aren't assigned currently as unassigned.

**Comment by IurmanJ** [comment]
Thanks for the feedback, Frank. I modified the last commit to reflect what you suggest, i.e., [dfcb1c9](https://github.com/inband-oam/ietf/pull/246/commits/dfcb1c9130a048fa9520458d081129588cbb183d).

**Comment by brockners** [comment]
Thanks Justin. Let's get things merged and a new revision published - so that we hit the IETF 113 deadline.
Could you take care of publishing the new revision?

Thanks, Frank

**Comment by IurmanJ** [comment]
I'll let you merge the PR as I don't have the rights to do so. I guess you'll also have to push a commit to update the draft version before we publish it. Anyway, would I be able to publish the revision? Officially, I'm still not an author of this draft on datatracker (since I'm not in -00), so I'm wondering if it's possible. I did not go through this process yet, could you describe the procedure to do so?

**Pull request merged**
