### PR TITLE
Update draft-ietf-ippm-ioam-data.xml

### PR DESCRIPTION
**Pull request by jalemon**
Rewrote Loopback bit text

### CODE REVIEW

**Comment by brockners** [comment]
Thanks John. Your description nicely captures loopback mode. If others are ok, we can merge your patch.

**Comment by jalemon** [comment]
Sorry, I don't understand the question "How do you police the loopback packet?" Are you asking how we limit who sets the loopback bit? Are you asking how we control what is done with the loopback while it is returning?

**Comment by rsivakolundu** [comment]
Hi John,

Sorry for the delayed response. I was asking how to monitor or police who sets the loopback bit.

**Comment by jalemon** [comment]
Hi Ramesh,

I don't think it is possible to prevent anymore than it is possible to prevent any other illegal packet setting.

Regards, John

**Pull request merged**
