### PR TITLE
Active flag for probes and cloned packets

### PR DESCRIPTION
**Pull request by mickeyspiegel**
Proposes to assign a flag bit for indication of "active OAM", for example
probes and cloned packets.

When "active OAM" is indicated, at the IOAM decapsulating node the packet
is discarded rather than forwarded, after retrieval of the IOAM metadata.

### CODE REVIEW

**Comment by jalemon** [comment]
I'm not liking the nomenclature. Can we call it a "probe" packet instead of an "active" packet? Active implies that the packet does something. Otherwise, looks fine to me.

**Comment by mickeyspiegel** [comment]
Active refers to active OAM. It is not just for probes. Whenever you are sending extra packets, whether that be probes or packet clones, I consider that to be active OAM as opposed to the in-situ which is hybrid OAM.

**Comment by jalemon** [comment]
Although we are familiar with active, passive, and hybrid OAM, I don't think the average person reading IOAM will know what active means in this context. Cloned traffic being sent only for OAM measuring is still a form of data probe.

**Comment by barakgafni** [comment]
I second John, active doesn't make sense to me. I think that probe is better understood for readers

**Comment by barakgafni** [comment]
Line 466: Mickey, can you please elaborate about the option to send the data back to the encapsulator? Do you mean when the A bit is set together with the loopback?

**Comment by mickeyspiegel** [comment]
@barakgafni That is old text that I left unchanged. I assume that refers to A bit with loopback.

**Comment by barakgafni** [comment]
should we delete it, or add a comment for clarification?
Not sure if we want to discuss every combination of these bits

**Comment by mickeyspiegel** [comment]
@barakgafni Deletion sounds good to me.

**Pull request merged**
